NHS.UK prototype re-design
nhs-pycom/nhs.pycom pull request #5
Opened 2021-05-03 13:31 UTC by craig-shenton

Re-design following Digital Service Manual principles and SEO improvements .

2021-05-04 07:06 UTC, maryamanuelnhsx requested changes
Hi @craig-shenton. this is absolutely **OUTSTANDING!**. I can't thank you enough for your hard work in re-designing this website to make it in line with NHS front end design principles and having a think about SEO.  Pycom website is **much more** functional now, thank you. 

There are some minor changes to be made before merging to main, mainly around the code of conduct doc, contents page reordering and minor typos. Then it should be good to go ask v2. There are also a few thing I'd like to discuss in person but we can do that on wednesday. 

Thanks again, brilliant work as always. This needs to be shared with the AU at some point :)

2021-05-04 07:14 UTC, maryamanuelnhsx commented on python-resources.html
> +              <p class="nhsuk-card__description">A list of Python books in English that are free to read online or download..</p>
> @craig-shenton - super minor edit, remove the double full stop.

@craig-shenton next to "online and download"

2021-05-07 08:47 UTC, maryamanuelnhsx commented on code-of-conduct.html
> +
@Arouba will update this.

2021-05-08 15:23 UTC, craig-shenton commented on index.html
> +      </header>
Home was hidden except on mobile, now shows on desktop view

2021-05-10 06:23 UTC, maryamanuelnhsx commented on index.html
> +      </header>
looks great @craig-shenton

2021-05-10 07:55 UTC, craig-shenton commented
Footer on all pages need to copy index.html

2021-05-10 08:55 UTC, Arouba commented on code-of-conduct.html
> +
Updated

2021-05-10 08:57 UTC, merged